### ISSUE TITLE
Make site loading faster by minifying CSS 

### ISSUE THREAD

**Issue by fxm90** [JohnSundell/swiftbysundell-beta-feedback#10]
I saw that the page source is already minified 👍 You could do the same with your CSS code, to make the site load even faster 🚀😅

**Comment by jshier** [comment]
Cloudflare should have a setting to do this automatically.

**Comment by JohnSundell** [comment]
Totally. Haven't enabled any optimizations there yet (the HTML minimization is performed by my site generator), but will definitely do it before shipping. Thanks guys! 👍

**Comment by JohnSundell** [comment]
Fix deployed ✅
