### ISSUE TITLE
logo.png should be optimized

### ISSUE THREAD

**Issue by jshier** [JohnSundell/swiftbysundell-beta-feedback#11]
Similar to #10, you can save 25KB of transfer by crushing the logo. I've attached the one I did using ImageOptim.

![logo](https://user-images.githubusercontent.com/51020/63462041-00a41500-c428-11e9-9d9f-fe02ff4b9e17.png)

**Comment by JohnSundell** [comment]
Thanks a lot! Still planning to do some tweaks to the image itself, so will run optimizations on it once I'm 100% done 👍

**Comment by jshier** [comment]
Cloudflare can do this too, if you have one of the higher level paid plans.

**Comment by JohnSundell** [comment]
Fix deployed ✅
