### ISSUE TITLE
Tag headline gets broken into multiple lines on small screen

### ISSUE THREAD

**Issue by mannberg** [JohnSundell/swiftbysundell-beta-feedback#12]
![589D98B7-E433-4310-AC2F-A08C3EB1430E](https://user-images.githubusercontent.com/10973214/63463163-ea647c00-c45c-11e9-9a30-790864484c6f.jpeg)

**Comment by JohnSundell** [comment]
Thanks a lot @mannberg! I just deployed a fix that mitigates this issue (and fixes another one - fixing bugs is a bit like playing wack-a-mole, isn't it 😅). I'll leave this open for now until I can thoroughly fix it 👍

**Comment by mannberg** [comment]
@johnsundell No worries, thank you for bringing our beloved Swift into the web domain! 😁 I’ll gladly help by pointing out, or even wack, a mole or two! 🔨

**Comment by JohnSundell** [comment]
Closing this. The current solution looks good to me, and while it could use some tweaking for multi-line tags, I think it's good enough to ship 🚢
