### ISSUE TITLE
Menu can do with a bit more padding

### ISSUE THREAD

**Issue by icanzilb** [JohnSundell/swiftbysundell-beta-feedback#14]
It feels to me the menu items are too close to each other - they currently have only 10px padding. 

Here's how it'd look like with 15px:

![image](https://user-images.githubusercontent.com/633862/63470851-f4db4180-c46d-11e9-9603-fd51a6b9d226.png)

And here's how it looks like with a "&middot;" in between:

![image](https://user-images.githubusercontent.com/633862/63470867-0290c700-c46e-11e9-9f3b-4579e1c39a10.png)

🤷🏽‍♂️

**Comment by JohnSundell** [comment]
Thanks a lot @icanzilb, I'll look into increasing the padding a bit. I think 15px might be a bit too much, but perhaps something like 12px will do the trick. I'll see what I can do 🙂

**Comment by joeblau** [comment]
Had a similar comment on content. The site looks amazing. I also can't wait for you to release the engine beneath this beast.

One thing I was going to suggest is to add a little more space around the content of your cells. Right now I think your padding is set to 12px 14px. I changed it to 18px.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/1218847/63583040-34865400-c568-11e9-9dc2-fbd2b328ec25.png">

Here is the change also applied on the main landing page

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/1218847/63583203-89c26580-c568-11e9-9e37-605c1ac08059.png">


In a lot of cases, it doesn't affect the layout, but it does provide a big more separation around some of the content.

**Comment by JohnSundell** [comment]
Thanks a lot for your suggestions. However, after trying them out I've decided to stick with the current layout (I did tweak the margin a bit for the search icon though). Thanks anyway, and keep the feedback coming 🙂
