### ISSUE TITLE
Render dates in a more human-friendly way

### ISSUE THREAD

**Issue by JohnSundell** [JohnSundell/swiftbysundell-beta-feedback#15]
Right now all dates on the site are rendered using the `yyyy-MM-dd` format, which could be improved. Experiment with different date formats to come up with something nice (perhaps stick with the format that the previous site is using: `Jan 17 2018`).

**Comment by PaulSolt** [comment]
+1 on Jan 17, 2018

**Comment by JohnSundell** [comment]
Fixed deployed ✅

**Comment by Jimmy-Prime** [comment]
Will date format takes locale into account? In our country, we do actually prefer the `yyyy/mm/dd` format.

**Comment by JohnSundell** [comment]
I’m afraid not, since it’s a static site it’ll be the same for everyone.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
