### ISSUE TITLE
Extra padding between last and second to last items in the menu

### ISSUE THREAD

**Issue by icanzilb** [JohnSundell/swiftbysundell-beta-feedback#19]
When you're on the Newsletter page, hover with the mouse over the Sponsorship menu item - you will see an extra line of padding between them (unlike the rest of the menu items):

![image](https://user-images.githubusercontent.com/633862/63473124-a1b8bd00-c474-11e9-83c5-dabff3879150.png)

**Comment by JohnSundell** [comment]
Thanks a lot for reporting this @icanzilb!

**Comment by TommiKivimaki** [comment]
I saw this issue also with Safari 12.1.2. When I changed the width of the browser window the white thin line was shown between different menu items e.g. between "Newsletter" and "Tips".

**Comment by JohnSundell** [comment]
Fix deployed ✅
