### ISSUE TITLE
Menu Pops when clicking between different tabs

### ISSUE THREAD

**Issue by PaulSolt** [JohnSundell/swiftbysundell-beta-feedback#20]
The menu "flashes" and changes when navigating between different sections.

I'd expect that if it's the same content (header) it would not shift/reload. 

I don't know if this is a rendering issue, or if there's another way to get around it. Sometimes it seems to be ok and other times it reloads everything.

**Comment by JohnSundell** [comment]
This is very much depending on the browser. All that I'm sending is static HTML, there's no async rendering or anything like that going on, so I don't think there's anything do be done here. Thanks a lot for the feedback though 👍
