### ISSUE TITLE
Menu spacer is not always visible

### ISSUE THREAD

**Issue by PaulSolt** [JohnSundell/swiftbysundell-beta-feedback#21]
There is a spacer that appears if you are hovering over one of the tabs to click on.

It only appears on one side, not the other, leaving a disconnect.

Left button is selected, right is hovered:

<img width="670" alt="Screen Shot 2019-08-22 at 5 36 30 PM" src="https://user-images.githubusercontent.com/371902/63551595-9365b200-c503-11e9-9e91-7c96b391457d.png">

Right button is selected, left is hovered:

<img width="547" alt="Screen Shot 2019-08-22 at 5 38 05 PM" src="https://user-images.githubusercontent.com/371902/63551646-ad9f9000-c503-11e9-8084-cc6aadc7d908.png">

**Comment by JohnSundell** [comment]
Thanks a lot for reporting this @PaulSolt, but it's essentially the same issue as #19, so closing this as a duplicate 🙂
