### ISSUE TITLE
Meaningful Color Schemes

### ISSUE THREAD

**Issue by codeface-io** [JohnSundell/swiftbysundell-beta-feedback#23]
Great work so far!

The first and only thing I find irritating are the colors. I would prefer that background colors are darker than the content elements in front of it. 

Example: The front page in dark mode. Try making the page background black and the content boxes dark grey (basically switch). I know this reduces contrast with text a bit, but I find that easier on the eyes. The same for light mode: Try Grey background and white content ...

I'm used to the idea that the foreground is brighter, not just from macOS, YouTube and material design but also from real-world perception.

**Comment by JohnSundell** [comment]
Hi @flowtoolz, thanks a lot for that feedback - but I like the color hierarchy the way it is. I'm aware of the trend to illustrate depth using lighter colors, but that's not what I'm going for with this design. The one thing I will do is make sure that the dark mode colors are fully accessible as per #16. Closing this, but thanks again anyway 🙂
