### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Malauch** [JohnSundell/swiftbysundell-beta-feedback#24]
When trying to search something is like nothing happend. Page is reloading but no result are shown.

I'm using Safari on MacOS 10.14.6

**Comment by JohnSundell** [comment]
Thanks for reporting this @Malauch. Do you see the text that says *No results found for **query***, or is the page just empty? Could you also verify that there's a successful SSL connection (there's a lock icon in the address bar). Thanks!

**Comment by Malauch** [comment]
It's strange, because yesterday it didn't work. After the search, page was reloaded but looks the same  like before clicking search. Now I wanted to record screencast but it is working right now. However, still result are not exhaustive. For example when searching for phrase "map", article from Basics category is missing.

Search results
![image](https://user-images.githubusercontent.com/13001524/64059816-b1967680-cbc3-11e9-93cf-93bee6a78ded.jpg)

Basics category
![image-kopia](https://user-images.githubusercontent.com/13001524/64059817-b3f8d080-cbc3-11e9-94a2-74505a834a0f.jpeg)

**Comment by JohnSundell** [comment]
Thanks again @Malauch, I really appreciate you taking the time to report these issues. So regarding search now working, I'm quite confident that it's some form of SSL issue, which I'm currently looking into. It looks like SSL is dropped for certain requests, which would explain why your original search didn't go through. Regarding that the *Map, FlatMap and CompactMap* article didn't show up, that was a bug in my search index generation code, which I've now deployed a fix for 😀 So closing this issue for now, but feel free to let me know if there are any other results that you find missing from search 👍
