### ISSUE TITLE
Need Controls for Speeding Up Podcasts

### ISSUE THREAD

**Issue by nick28** [JohnSundell/swiftbysundell-beta-feedback#25]
Love your content. I have just started listening to your Podcast, and it would be great if there are controls to speed up Podcasts. Just a suggestion that might be useful, right now using 
document querySelector to edit the playback rate

**Comment by JohnSundell** [comment]
Hi @nick28, thanks a lot for the feedback, and I'm glad to hear that you enjoy my work. I recommend using a proper podcast player to listen to my podcast - for example Apple Podcasts, Overcast, or Pocket Casts. You can find links to subscribe to Swift by Sundell in several of those apps directly from each episode page. Those apps offer a lot of control over the playback speed, among other features, so it's not something I consider worth implementing on my own. Thanks anyway 🙂
