### ISSUE TITLE
Full stop in website header wraps to new line by itself

### ISSUE THREAD

**Issue by lordcodes** [JohnSundell/swiftbysundell-beta-feedback#8]
On smaller screen size the full stop at the end of the heading in the main website header can wrap to a new line by itself. This looks a little out of place by itself.

**Comment by JohnSundell** [comment]
Hi @lordcodes. Thanks a lot for filing this issue. Do you mind attaching a screenshot so that I can see exactly what you mean? 🙂

**Comment by lordcodes** [comment]
Sure, I was going to add that when i got a chance.

**Comment by JohnSundell** [comment]
@lordcodes is it the same issue as this? https://twitter.com/neilgmacy/status/1164251185404153856

**Comment by lordcodes** [comment]
Yes, exactly what i was trying to describe 😛

**Comment by JohnSundell** [comment]
Ah, perfect. Then a screenshot is not needed. Thanks a lot, will fix it tonight 😀

**Comment by lordcodes** [comment]
No problem! 👍

**Comment by JohnSundell** [comment]
I've just deployed a fix for this - let me know if it's still an issue and I'll re-open. Thanks so much again @lordcodes 🙌
